// network events
export const ERROR_EVENT = "ERROR"
export const CHAT_EVENT = "CHAT"
export const AUTH_EVENT = "AUTH"
export const PLAYER_EVENT = "PLAYER"
export const SERVER_LOG_EVENT = "SERVER_LOG"
export const ROOM_UPDATE_EVENT = "ROOM_UPDATE"
export const ROLL_EVENT = "ROLL"
export const MAKE_ROOM_EVENT = "MAKE_ROOM"
export const GO_EVENT = "GO"
export const USERNAME_CHANGE_EVENT = "USERNAME_CHANGE"
export const PING_EVENT = "PING"
export const CHAT_HISTORY_EVENT = "CHAT_HISTORY"
export const LOOK_EVENT = "LOOK"
export const DRAW_EVENT = "DRAW"
export const MAKE_DOOR_EVENT = "MAKE_DOOR"
export const TP_EVENT = "TP"
export const DELETE_DOOR_EVENT = "DELETE_DOOR"
export const ROOM_DESCRIBE_EVENT = "DESCRIBE"
export const SHOUT_EVENT = "SHOUT"
export const WHISPER_EVENT = "WHISPER"
export const ME_EVENT = "ME"
export const ONLINE_EVENT = "ONLINE"
export const MAKE_ITEM_EVENT = "MAKE_ITEM"
export const INV_EVENT = "INV"
export const DROP_ITEM_EVENT = "DROP_ITEM"
export const TAKE_ITEM_EVENT = "TAKE_ITEM"
export const LOOK_AT_EVENT = "LOOK_AT"
export const PAY_EVENT = "PAY"
export const INBOX_EVENT = "INBOX"
export const INBOX_HISTORY_EVENT = "INBOX_HISTORY"
export const WHISPER_LOG_EVENT = "WHISPER_LOG"
export const NOTIFICATION_EVENT = "NOTIFICATION"

// command events
export const LOG_EVENT = "LOG"
export const INPUT_EVENT = "INPUT"
