import { getConstantValue } from "typescript";
import validateColor from "validate-color";

import { ColorTheme } from "../types/ColorTheme";

const VALID_COLOR_KEYS = [
  "name",
  "toolbar-back",
  "toolbar-edge",
  "toolbar-title",
  "toolbar-button-back",
  "toolbar-button-logos",
  "toolbar-button-back-hover",
  "toolbar-button-logos-hover",
  "toolbar-button-edge",
  "toolbar-button-edge-hover",
  "toolbar-dropdown-back",
  "toolbar-dropdown-text",
  "toolbar-dropdown-edge",
  "toolbar-dropdown-shadow",
  "toolbar-hovernames-back",
  "toolbar-hovernames-text",
  "toolbar-hovernames-edge",
  "toolbar-slider-back",
  "toolbar-slider-back-edge",
  "toolbar-slider-thumb",
  "toolbar-slider-thumb-edge",
  "toolbar-slider-back-hover",
  "toolbar-slider-back-edge-hover",
  "toolbar-slider-thumb-hover",
  "toolbar-slider-thumb-edge-hover",
  "toolbar-charlimit",
  "toolbar-charlimit-over",
  "toolbar-charlimit-back",
  "toolbar-charlimit-over-back",
  "toolbar-input-text",
  "toolbar-input-back",
  "toolbar-input-edge",
  "toolbar-publish-button-text",
  "toolbar-publish-button-back",
  "toolbar-publish-button-edge",
  "toolbar-publish-button-text-hover",
  "toolbar-publish-button-back-hover",
  "toolbar-publish-button-edge-hover",
  "toolbar-sub-button-text",
  "toolbar-sub-button-back",
  "toolbar-sub-button-edge",
  "toolbar-sub-button-text-hover",
  "toolbar-sub-button-back-hover",
  "toolbar-sub-button-edge-hover",
  "toolbar-palette-text",
  "toolbar-palette-back",
  "toolbar-palette-text-hover",
  "toolbar-palette-back-hover",
  "banner-line",
  "banner-mini",
  "banner-mini-edge",
  "banner-mini-back", 
  "banner-mini-hover",
  "banner-mini-edge-hover",
  "banner-mini-back-hover", 
  "banner-type",
  "banner-type-back",
  "banner-type-edge",
  "banner-type-hover",
  "banner-type-back-hover",
  "banner-type-edge-hover",
  "banner-type-select",
  "banner-type-select-back",
  "banner-type-select-back-edge",
  "banner-color",
  "banner-back",
  "banner-border",
  "banner-cursor",
  "banner-cursor-back",
  "banner-room-name",
  "terminal-back",
  "text-primary",
  "text-link",
  "chat-date",
  "chat-name",
  "chat-message",
  "chat-error",
  "charlimit",
  "charlimit-over",
  "input-text",
  "input-back",
  "input-back-edge",
  "scrollbar-back",
  "scrollbar-thumb",
  "scrollbar-back-edge",
  "scrollbar-thumb-edge",
  "background-primary",
  "background-code",
  "divider",
];

export const VALID_COLOR_THEMES = [
  "dark",
  "amiga",
  "commodore",
  "green",
  "amber",
  "cga",
  "windows",
  "dmg",
  "light",
  "pink",
  "emo",
  "aol",
  "ds",
  "teletext",
  "myspace",
  "runescape",
];

const dark: ColorTheme = {
  "name": "dark",
  "toolbar-back": "white",
  "toolbar-edge": "none",
  "toolbar-title": "black",
  "toolbar-button-back": "rbg(0,0,0,0)",
  "toolbar-button-logos": "black",
  "toolbar-button-back-hover": "black",
  "toolbar-button-logos-hover": "white",
  "toolbar-button-edge": "none",
  "toolbar-button-edge-hover": "none",
  "toolbar-dropdown-back": "white",
  "toolbar-dropdown-text": "black",
  "toolbar-dropdown-edge": "none",
  "toolbar-dropdown-shadow": "none",
  "toolbar-hovernames-back": "black",
  "toolbar-hovernames-text": "white",
  "toolbar-hovernames-edge": "none",
  "toolbar-slider-back": "grey",
  "toolbar-slider-back-edge": "none",
  "toolbar-slider-thumb": "black",
  "toolbar-slider-thumb-edge": "none",
  "toolbar-slider-back-hover": "black",
  "toolbar-slider-back-edge-hover": "none",
  "toolbar-slider-thumb-hover": "grey",
  "toolbar-slider-thumb-edge-hover": "none",
  "toolbar-charlimit": "black",
  "toolbar-charlimit-over": "magenta",
  "toolbar-charlimit-back": "rbg(0,0,0,0)",
  "toolbar-charlimit-over-back": "rbg(0,0,0,0)",
  "toolbar-input-text": "black",
  "toolbar-input-back": "rbg(0,0,0,0)",
  "toolbar-input-edge": "none",
  "toolbar-publish-button-text": "black",
  "toolbar-publish-button-back": "rbg(0,0,0,0)",
  "toolbar-publish-button-edge": "none",
  "toolbar-publish-button-text-hover": "white",
  "toolbar-publish-button-back-hover": "black",
  "toolbar-publish-button-edge-hover": "none",
  "toolbar-sub-button-text":"black",
  "toolbar-sub-button-back":"rbg(0,0,0,0)",
  "toolbar-sub-button-edge":"none",
  "toolbar-sub-button-text-hover":"white",
  "toolbar-sub-button-back-hover":"black",
  "toolbar-sub-button-edge-hover":"none",
  "toolbar-palette-text":"black",
  "toolbar-palette-back":"rbg(0,0,0,0)",
  "toolbar-palette-text-hover":"magenta",
  "toolbar-palette-back-hover":"rbg(0,0,0,0)",  
  "banner-line":"1px solid white",
  "banner-mini":"white",
  "banner-mini-edge":"none",
  "banner-mini-hover":"rgb(255,255,255,0.5)",
  "banner-mini-back":"rgb(0,0,0,0)",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"rgb(0,0,0,0)",
  "banner-type":"white",
  "banner-type-back":"rgb(0,0,0,0)",
  "banner-type-edge":"none",
  "banner-type-hover":"rgb(255,255,255,0.5)",
  "banner-type-back-hover":"rgb(0,0,0,0)",
  "banner-type-edge-hover":"none",
  "banner-type-select": "black",
  "banner-type-select-back": "white",
  "banner-type-select-back-edge":"none",
  "banner-color":"white",
  "banner-back":"rgb(0,0,0,0)",
  "banner-border":"none",
  "banner-cursor":"magenta",
  "banner-cursor-back":"rgb(255,255,255,0.5)",
  "banner-room-name":"white",
  "terminal-back":"rgb(0,0,0,0)",
  "text-primary": "white",
  "text-link": "magenta",
  "chat-date": "white",
  "chat-name": "magenta",
  "chat-message": "white",
  "chat-error": "red",
  "charlimit": "white",
  "charlimit-over": "magenta",
  "input-text": "white",
  "input-back": "black",
  "input-back-edge": "none", 
  "scrollbar-back": "black",
  "scrollbar-thumb": "white",
  "scrollbar-back-edge": "none",
  "scrollbar-thumb-edge": "none",
  "background-primary": "black",
  "background-code": "magenta",
  "divider": "rgb(255,255,255,0.5)",
}

const amiga: ColorTheme = {
  "name": "amiga",
  "toolbar-back": "white",
  "toolbar-edge": "none",
  "toolbar-title": "#0055ab",
  "toolbar-button-back": "rgb(0,0,0,0)",
  "toolbar-button-logos": "#0055ab",
  "toolbar-button-back-hover": "#f5690d",
  "toolbar-button-logos-hover": "black",
  "toolbar-button-edge": "none",
  "toolbar-button-edge-hover": "none",
  "toolbar-dropdown-back": "#0055ab",
  "toolbar-dropdown-text": "white",
  "toolbar-dropdown-edge": "4px solid white",
  "toolbar-dropdown-shadow": "none",
  "toolbar-hovernames-back": "#0055ab",
  "toolbar-hovernames-text": "white",
  "toolbar-hovernames-edge": "4px solid white",
  "toolbar-slider-back": "#0055ab",
  "toolbar-slider-back-edge": "2px solid white",
  "toolbar-slider-thumb": "white",
  "toolbar-slider-thumb-edge": "none",
  "toolbar-slider-back-hover": " #0055ab",
  "toolbar-slider-back-edge-hover": "2px solid white",
  "toolbar-slider-thumb-hover": "white",
  "toolbar-slider-thumb-edge-hover": "none",
  "toolbar-charlimit": "white",
  "toolbar-charlimit-over": "#f5690d",
  "toolbar-charlimit-back": "rgb(0,0,0,0)",
  "toolbar-charlimit-over-back": "rgb(0,0,0,0)",
  "toolbar-input-text": "white",
  "toolbar-input-back": "#0055ab",
  "toolbar-input-edge": "2px solid white",
  "toolbar-publish-button-text": "#0055ab",
  "toolbar-publish-button-back": "white",
  "toolbar-publish-button-edge": "none",
  "toolbar-publish-button-text-hover": "black",
  "toolbar-publish-button-back-hover": "#f5690d",
  "toolbar-publish-button-edge-hover": "none",
  "toolbar-sub-button-text":"#0055ab",
  "toolbar-sub-button-back":"white",
  "toolbar-sub-button-edge": "none",
  "toolbar-sub-button-text-hover":"black",
  "toolbar-sub-button-back-hover":"#f5690d",
  "toolbar-sub-button-edge-hover":"none",
  "toolbar-palette-text":"white",
  "toolbar-palette-back":"none",
  "toolbar-palette-text-hover":"#f5690d",
  "toolbar-palette-back-hover":"none",
  "banner-line":"10px solid white",
  "banner-mini":"white",
  "banner-mini-edge":"none",
  "banner-mini-hover":"black",
  "banner-mini-back":"none",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"none",
  "banner-type":"white",
  "banner-type-back":"none",
  "banner-type-edge":"none",
  "banner-type-hover":"black",
  "banner-type-back-hover":"none",
  "banner-type-edge-hover":"none",
  "banner-type-select": "#0055ab",
  "banner-type-select-back": "white",
  "banner-type-select-back-edge":"none",
  "banner-color":"white",
  "banner-back":"none",
  "banner-border":"4px solid white",
  "banner-cursor":"black",
  "banner-cursor-back":"#f5690d",
  "banner-room-name":"white",
  "terminal-back":"black",
  "text-primary": "white",
  "text-link": "#f5690d",
  "chat-date": "white",
  "chat-name": "#f5690d",
  "chat-error": "#f5690d",
  "chat-message": "white",
  "charlimit": "white",
  "charlimit-over": "#f5690d",
  "input-text": "white",
  "input-back": "none",
  "input-back-edge": "4px solid white", 

  "scrollbar-back": "none",
  "scrollbar-thumb": "white",
  "scrollbar-back-edge": "4px solid white",
  "scrollbar-thumb-edge": "none",

  "background-primary": "#0055ab",
  "background-code": "#f5690d",
  "divider": "white",
}
const commodore: ColorTheme = {
  "name": "commodore",
  "toolbar-back": "#8677e1",
  "toolbar-edge": "none",
  "toolbar-title": "#4835ad",
  "toolbar-button-back": "none",
  "toolbar-button-logos": "#4835ad",
  "toolbar-button-back-hover": "#4835ad",
  "toolbar-button-logos-hover": "#8677e1",
  "toolbar-button-edge": "none",
  "toolbar-button-edge-hover": "none",
  "toolbar-dropdown-back": "#8677e1",
  "toolbar-dropdown-text": "#4835ad",
  "toolbar-dropdown-edge": "none",
  "toolbar-dropdown-shadow": "none",
  "toolbar-hovernames-back": "#4835ad",
  "toolbar-hovernames-text": "#84cdcf",
  "toolbar-hovernames-edge": "none",
  "toolbar-slider-back": "#4835ad",
  "toolbar-slider-back-edge": "none",
  "toolbar-slider-thumb": "#8677e1",
  "toolbar-slider-thumb-edge": "none",
  "toolbar-slider-back-hover": "#4835ad",
  "toolbar-slider-back-edge-hover": "none",
  "toolbar-slider-thumb-hover": "#8677e1",
  "toolbar-slider-thumb-edge-hover": "none",
  "toolbar-charlimit": "#4835ad",
  "toolbar-charlimit-over": "#84cdcf",
  "toolbar-charlimit-back": "none",
  "toolbar-charlimit-over-back": "none",
  "toolbar-input-text": "#8677e1",
  "toolbar-input-back": "#4835ad",
  "toolbar-input-edge": "none",
  "toolbar-publish-button-text": "#8677e1",
  "toolbar-publish-button-back": "#4835ad",
  "toolbar-publish-button-edge": "none",
  "toolbar-publish-button-text-hover": "#d9e474",
  "toolbar-publish-button-back-hover": "#4835ad",
  "toolbar-publish-button-edge-hover": "none",
  "toolbar-sub-button-text":"#8677e1",
  "toolbar-sub-button-back":"#4835ad",
  "toolbar-sub-button-edge": "none",
  "toolbar-sub-button-text-hover":"#d9e474",
  "toolbar-sub-button-back-hover":"#4835ad",
  "toolbar-sub-button-edge-hover":"none",
  "toolbar-palette-text":"#4835ad",
  "toolbar-palette-back":"none",
  "toolbar-palette-text-hover":"#d9e474",
  "toolbar-palette-back-hover":"none",
  "banner-line":"none",
  "banner-mini":"#8677e1",
  "banner-mini-edge":"none",
  "banner-mini-hover":"#d9e474",
  "banner-mini-back":"none",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"none",
  "banner-type":"#8677e1",
  "banner-type-back":"none",
  "banner-type-edge":"none",
  "banner-type-hover":"#d9e474",
  "banner-type-back-hover":"none",
  "banner-type-edge-hover":"none",
  "banner-type-select": "#4835ad",
  "banner-type-select-back": "#8677e1",
  "banner-type-select-back-edge":"none",
  "banner-color":"#8677e1",
  "banner-back":"none",
  "banner-border":"50px solid #8677e1",
  "banner-cursor":"#d9e474",
  "banner-cursor-back":"none",
  "banner-room-name":"#8677e1",
  "terminal-back":"rgb(0,0,0,0)",
  "text-primary": "#8677e1",
  "text-link": "#d9e474",
  "chat-date": "#84cdcf",
  "chat-name": "#d9e474",
  "chat-error": "red",
  "chat-message": "#84cdcf",
  "charlimit": "#8677e1",
  "charlimit-over": "#8677e1",
  "input-text": "#d9e474",
  "input-back": "none",
  "input-back-edge": "none", 

  "scrollbar-back": "none",
  "scrollbar-thumb": "#8677e1",
  "scrollbar-back-edge": "none",
  "scrollbar-thumb-edge": "none",

  "background-primary": "#4835ad",
  "background-code": "#84cdcf",
  "divider": "#8677e1",
}
const green: ColorTheme = {
  "name": "green",
  "toolbar-back": "#019f02",
  "toolbar-edge": "none",
  "toolbar-title": "#023401",
  "toolbar-button-back": "none",
  "toolbar-button-logos": "#023401",
  "toolbar-button-back-hover": "#00ef11",
  "toolbar-button-logos-hover": "#023401",
  "toolbar-button-edge": "none",
  "toolbar-button-edge-hover": "none",
  "toolbar-dropdown-back": "#019f02",
  "toolbar-dropdown-text": "#023401",
  "toolbar-dropdown-edge": "none",
  "toolbar-dropdown-shadow": "none",
  "toolbar-hovernames-back": "#00ef11",
  "toolbar-hovernames-text": "#023401",
  "toolbar-hovernames-edge": "none",
  "toolbar-slider-back": "#023401",
  "toolbar-slider-back-edge": "none",
  "toolbar-slider-thumb": "#00ef11",
  "toolbar-slider-thumb-edge": "none",
  "toolbar-slider-back-hover": "#023401",
  "toolbar-slider-back-edge-hover": "none",
  "toolbar-slider-thumb-hover": "#00ef11",
  "toolbar-slider-thumb-edge-hover": "none",
  "toolbar-charlimit": "#023401",
  "toolbar-charlimit-over": "#00ef11",
  "toolbar-charlimit-back": "none",
  "toolbar-charlimit-over-back": "#023401",
  "toolbar-input-text": "#00ef11",
  "toolbar-input-back": "#023401",
  "toolbar-input-edge": "none",
  "toolbar-publish-button-text": "#019f02",
  "toolbar-publish-button-back": "#00ef11",
  "toolbar-publish-button-edge": "none",
  "toolbar-publish-button-text-hover": "#00ef11",
  "toolbar-publish-button-back-hover": "#023401",
  "toolbar-publish-button-edge-hover": "none",
  "toolbar-sub-button-text":"#019f02",
  "toolbar-sub-button-back":"#00ef11",
  "toolbar-sub-button-edge": "none",
  "toolbar-sub-button-text-hover":"#00ef11",
  "toolbar-sub-button-back-hover":"#023401",
  "toolbar-sub-button-edge-hover":"none",
  "toolbar-palette-text":"#00ef11",
  "toolbar-palette-back":"#019f02",
  "toolbar-palette-text-hover":"#023401",
  "toolbar-palette-back-hover":"#00ef11",
  "banner-line":"2px solid #00ef11",
  "banner-mini":"#00ef11",
  "banner-mini-edge":"none",
  "banner-mini-hover":"#019f02",
  "banner-mini-back":"none",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"none",
  "banner-type":"#00ef11",
  "banner-type-back":"none",
  "banner-type-edge":"none",
  "banner-type-hover":"#019f02",
  "banner-type-back-hover":"none",
  "banner-type-edge-hover":"none",
  "banner-type-select": "#023401",
  "banner-type-select-back": "#00ef11",
  "banner-type-select-back-edge":"none",
  "banner-color":"#00ef11",
  "banner-back":"none",
  "banner-border":"none",
  "banner-cursor":"#019f02",
  "banner-cursor-back":"none",
  "banner-room-name":"#00ef11",

  "terminal-back":"none",
  "text-primary": "#00ef11",
  "text-link": "#00ef11",
  "chat-date": "#019f02",
  "chat-name": "#00ef11",
  "chat-error": "#00ef11",
  "chat-message": "#019f02",
  "charlimit": "#00ef11",
  "charlimit-over": "#00ef11",
  "input-text": "#00ef11",
  "input-back": "none",
  "input-back-edge": "none", 

  "scrollbar-back": "none",
  "scrollbar-thumb": "#00ef11",
  "scrollbar-back-edge": "none",
  "scrollbar-thumb-edge": "none",

  "background-primary": "#023401",
  "background-code": "#019f02",
  "divider": "#019f02",
}
const amber: ColorTheme = {
  "name": "amber",
  "toolbar-back": "#ffdb30",
  "toolbar-edge": "none",
  "toolbar-title": "#792400",
  "toolbar-button-back": "none",
  "toolbar-button-logos": "#792400",
  "toolbar-button-back-hover": "#eb7900",
  "toolbar-button-logos-hover": "#792400",
  "toolbar-button-edge": "none",
  "toolbar-button-edge-hover": "none",
  "toolbar-dropdown-back": "#ffdb30",
  "toolbar-dropdown-text": "#792400",
  "toolbar-dropdown-edge": "none",
  "toolbar-dropdown-shadow": "none",
  "toolbar-hovernames-back": "#792400",
  "toolbar-hovernames-text": "#ffdb30",
  "toolbar-hovernames-edge": "none",
  "toolbar-slider-back": "#792400",
  "toolbar-slider-back-edge": "none",
  "toolbar-slider-thumb": "#ffdb30",
  "toolbar-slider-thumb-edge": "none",
  "toolbar-slider-back-hover": "#792400",
  "toolbar-slider-back-edge-hover": "none",
  "toolbar-slider-thumb-hover": "#ffdb30",
  "toolbar-slider-thumb-edge-hover": "none",
  "toolbar-charlimit": "#792400",
  "toolbar-charlimit-over": "#ffdb30",
  "toolbar-charlimit-back": "none",
  "toolbar-charlimit-over-back": "#792400",
  "toolbar-input-text": "#ffdb30",
  "toolbar-input-back": "#792400",
  "toolbar-input-edge": "none",
  "toolbar-publish-button-text": "#ffdb30",
  "toolbar-publish-button-back": "#792400",
  "toolbar-publish-button-edge": "none",
  "toolbar-publish-button-text-hover": "#ffdb30",
  "toolbar-publish-button-back-hover": "#eb7900",
  "toolbar-publish-button-edge-hover": "none",
  "toolbar-sub-button-text":"#ffdb30",
  "toolbar-sub-button-back":"#792400",
  "toolbar-sub-button-edge": "none",
  "toolbar-sub-button-text-hover":"#ffdb30",
  "toolbar-sub-button-back-hover":"#eb7900",
  "toolbar-sub-button-edge-hover":"none",
  "toolbar-palette-text":"#ffdb30",
  "toolbar-palette-back":"#eb7900",
  "toolbar-palette-text-hover":"#792400",
  "toolbar-palette-back-hover":"#ffdb30",
  "banner-line":"2px solid #ffdb30",
  "banner-mini":"#ffdb30",
  "banner-mini-edge":"none",
  "banner-mini-hover":"#eb7900",
  "banner-mini-back":"none",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"none",
  "banner-type":"#ffdb30",
  "banner-type-back":"none",
  "banner-type-edge":"none",
  "banner-type-hover":"#eb7900",
  "banner-type-back-hover":"none",
  "banner-type-edge-hover":"none",
  "banner-type-select": "#792400",
  "banner-type-select-back": "#ffdb30",
  "banner-type-select-back-edge":"none",
  "banner-color":"#ffdb30",
  "banner-back":"none",
  "banner-border":"none",
  "banner-cursor":"#eb7900",
  "banner-cursor-back":"none",
  "banner-room-name":"#ffdb30",

  "terminal-back":"none",
  "text-primary": "#ffdb30",
  "text-link": "#ffdb30",
  "chat-date": "#eb7900",
  "chat-name": "#ffdb30",
  "chat-error": "#ffdb30",
  "chat-message": "#eb7900",
  "charlimit": "#ffdb30",
  "charlimit-over": "#ffdb30",
  "input-text": "#ffdb30",
  "input-back": "none",
  "input-back-edge": "none", 

  "scrollbar-back": "none",
  "scrollbar-thumb": "#ffdb30",
  "scrollbar-back-edge": "none",
  "scrollbar-thumb-edge": "none",

  "background-primary": "#792400",
  "background-code": "#eb7900",
  "divider": "#eb7900",
}
const cga: ColorTheme = {
  "name": "cga",
  "toolbar-back": "white",
  "toolbar-edge": "none",
  "toolbar-title": "black",
  "toolbar-button-back": "none",
  "toolbar-button-logos": "black",
  "toolbar-button-back-hover": "magenta",
  "toolbar-button-logos-hover": "black",
  "toolbar-button-edge": "none",
  "toolbar-button-edge-hover": "none",
  "toolbar-dropdown-back": "white",
  "toolbar-dropdown-text": "black",
  "toolbar-dropdown-edge": "none",
  "toolbar-dropdown-shadow": "none",
  "toolbar-hovernames-back": "cyan",
  "toolbar-hovernames-text": "black",
  "toolbar-hovernames-edge": "none",
  "toolbar-slider-back": "black",
  "toolbar-slider-back-edge": "none",
  "toolbar-slider-thumb": "magenta",
  "toolbar-slider-thumb-edge": "none",
  "toolbar-slider-back-hover": "black",
  "toolbar-slider-back-edge-hover": "none",
  "toolbar-slider-thumb-hover": "magenta",
  "toolbar-slider-thumb-edge-hover": "none",
  "toolbar-charlimit": "black",
  "toolbar-charlimit-over": "magenta",
  "toolbar-charlimit-back": "none",
  "toolbar-charlimit-over-back": "black",
  "toolbar-input-text": "white",
  "toolbar-input-back": "black",
  "toolbar-input-edge": "none",
  "toolbar-publish-button-text": "white",
  "toolbar-publish-button-back": "black",
  "toolbar-publish-button-edge": "none",
  "toolbar-publish-button-text-hover": "white",
  "toolbar-publish-button-back-hover": "magenta",
  "toolbar-publish-button-edge-hover": "none",
  "toolbar-sub-button-text":"white",
  "toolbar-sub-button-back":"black",
  "toolbar-sub-button-edge": "none",
  "toolbar-sub-button-text-hover":"white",
  "toolbar-sub-button-back-hover":"magenta",
  "toolbar-sub-button-edge-hover":"none",
  "toolbar-palette-text":"black",
  "toolbar-palette-back":"none",
  "toolbar-palette-text-hover":"magenta",
  "toolbar-palette-back-hover":"white",
  "banner-line":"1px solid white",
  "banner-mini":"white",
  "banner-mini-edge":"none",
  "banner-mini-hover":"magenta",
  "banner-mini-back":"none",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"none",
  "banner-type":"white",
  "banner-type-back":"none",
  "banner-type-edge":"none",
  "banner-type-hover":"magenta",
  "banner-type-back-hover":"none",
  "banner-type-edge-hover":"none",
  "banner-type-select": "black",
  "banner-type-select-back": "cyan",
  "banner-type-select-back-edge":"none",
  "banner-color":"white",
  "banner-back":"none",
  "banner-border":"none",
  "banner-cursor":"magenta",
  "banner-cursor-back":"white",
  "banner-room-name":"white",

  "terminal-back":"none",
  "text-primary": "white",
  "text-link": "cyan",
  "chat-date": "magenta",
  "chat-name": "cyan",
  "chat-error": "white",
  "chat-message": "white",
  "charlimit": "magenta",
  "charlimit-over": "white",
  "input-text": "white",
  "input-back": "none",
  "input-back-edge": "none", 

  "scrollbar-back": "none",
  "scrollbar-thumb": "magenta",
  "scrollbar-back-edge": "none",
  "scrollbar-thumb-edge": "none",

  "background-primary": "black",
  "background-code": "cyan",
  "divider": "magenta",
}
const windows: ColorTheme = {
  "name": "windows",
  "toolbar-back": "#0e0087",
  "toolbar-edge": "outset",
  "toolbar-title": "white",
  "toolbar-button-back": "rgb(200,200,200)",
  "toolbar-button-logos": "black",
  "toolbar-button-back-hover": "white",
  "toolbar-button-logos-hover": "black",
  "toolbar-button-edge": "outset",
  "toolbar-button-edge-hover": "inset",
  "toolbar-dropdown-back": "rgb(200,200,200)",
  "toolbar-dropdown-text": "black",
  "toolbar-dropdown-edge": "outset",
  "toolbar-dropdown-shadow": "0px 8px 16px 0px rgba(0,0,0,1)",
  "toolbar-hovernames-back": "rgb(200,200,200)",
  "toolbar-hovernames-text": "black",
  "toolbar-hovernames-edge": "outset",
  "toolbar-slider-back": "grey",
  "toolbar-slider-back-edge": "inset",
  "toolbar-slider-thumb": "white",
  "toolbar-slider-thumb-edge": "outset",
  "toolbar-slider-back-hover": "grey",
  "toolbar-slider-back-edge-hover": "inset",
  "toolbar-slider-thumb-hover": "white",
  "toolbar-slider-thumb-edge-hover": "inset",
  "toolbar-charlimit": "black",
  "toolbar-charlimit-over": "red",
  "toolbar-charlimit-back": "none",
  "toolbar-charlimit-over-back": "none",
  "toolbar-input-text": "black",
  "toolbar-input-back": "white",
  "toolbar-input-edge": "inset",
  "toolbar-publish-button-text": "black",
  "toolbar-publish-button-back": "rgb(200,200,200)",
  "toolbar-publish-button-edge": "outset",
  "toolbar-publish-button-text-hover": "black",
  "toolbar-publish-button-back-hover": "white",
  "toolbar-publish-button-edge-hover": "inset",
  "toolbar-sub-button-text":"black",
  "toolbar-sub-button-back":"rgb(200,200,200)",
  "toolbar-sub-button-edge": "outset",
  "toolbar-sub-button-text-hover":"black",
  "toolbar-sub-button-back-hover":"white",
  "toolbar-sub-button-edge-hover":"inset",
  "toolbar-palette-text":"black",
  "toolbar-palette-back":"white",
  "toolbar-palette-text-hover":"white",
  "toolbar-palette-back-hover":"#0e0087",
  "banner-line":"20px solid #0e0087",
  "banner-mini":"black",
  "banner-mini-edge":"outset",
  "banner-mini-hover":"white",
  "banner-mini-back":"white",
  "banner-mini-edge-hover":"inset",
  "banner-mini-back-hover":"grey",
  "banner-type":"rgb(200,200,200)",
  "banner-type-back":"grey",
  "banner-type-edge":"outset",
  "banner-type-hover":"black",
  "banner-type-back-hover":"rgb(200,200,200)",
  "banner-type-edge-hover":"outset",
  "banner-type-select": "white",
  "banner-type-select-back": "#0e0087",
  "banner-type-select-back-edge":"outset white",
  "banner-color":"white",
  "banner-back":"grey",
  "banner-border":"3px outset white",
  "banner-cursor":"white",
  "banner-cursor-back":"#0e0087",
  "banner-room-name":"white",

  "terminal-back":"rgb(200,200,200)",
  "text-primary": "black",
  "text-link": "black",
  "chat-date": "black",
  "chat-name": "black",
  "chat-error": "red",
  "chat-message": "black",
  "charlimit": "black",
  "charlimit-over": "black",
  "input-text": "black",
  "input-back": "white",
  "input-back-edge": "inset", 

  "scrollbar-back": "grey",
  "scrollbar-thumb": "rgb(200,200,200)",
  "scrollbar-back-edge": "grey",
  "scrollbar-thumb-edge": "rgb(200,200,200)",

  "background-primary": "#008483",
  "background-code": "white",
  "divider": "black",
}
const dmg: ColorTheme = {
  "name": "dmg",
  "toolbar-back": "#365d48",
  "toolbar-edge": "none",
  "toolbar-title": "#577c44",
  "toolbar-button-back": "none",
  "toolbar-button-logos": "#577c44",
  "toolbar-button-back-hover": "#2a453b",
  "toolbar-button-logos-hover": "#577c44",
  "toolbar-button-edge": "none",
  "toolbar-button-edge-hover": "none",
  "toolbar-dropdown-back": "#365d48",
  "toolbar-dropdown-text": "#577c44",
  "toolbar-dropdown-edge": "none",
  "toolbar-dropdown-shadow": "none",
  "toolbar-hovernames-back": "#2a453b",
  "toolbar-hovernames-text": "#577c44",
  "toolbar-hovernames-edge": "none",
  "toolbar-slider-back": "#577c44",
  "toolbar-slider-back-edge": "none",
  "toolbar-slider-thumb": "#2a453b",
  "toolbar-slider-thumb-edge": "none",
  "toolbar-slider-back-hover": "#577c44",
  "toolbar-slider-back-edge-hover": "none",
  "toolbar-slider-thumb-hover": "#2a453b",
  "toolbar-slider-thumb-edge-hover": "none",
  "toolbar-charlimit": "#577c44",
  "toolbar-charlimit-over": "#2a453b",
  "toolbar-charlimit-back": "none",
  "toolbar-charlimit-over-back": "#577c44",
  "toolbar-input-text": "#2a453b",
  "toolbar-input-back": "#577c44",
  "toolbar-input-edge": "none",
  "toolbar-publish-button-text": "#7f860f",
  "toolbar-publish-button-back": "#2a453b",
  "toolbar-publish-button-edge": "none",
  "toolbar-publish-button-text-hover": "#7f860f",
  "toolbar-publish-button-back-hover": "#577c44",
  "toolbar-publish-button-edge-hover": "none",
  "toolbar-sub-button-text":"#7f860f",
  "toolbar-sub-button-back":"#2a453b",
  "toolbar-sub-button-edge": "none",
  "toolbar-sub-button-text-hover":"#7f860f",
  "toolbar-sub-button-back-hover":"#577c44",
  "toolbar-sub-button-edge-hover":"none",
  "toolbar-palette-text":"#2a453b",
  "toolbar-palette-back":"#365d48",
  "toolbar-palette-text-hover":"#577c44",
  "toolbar-palette-back-hover":"#2a453b",
  "banner-line":"2px solid #2a453b",
  "banner-mini":"#2a453b",
  "banner-mini-edge":"none",
  "banner-mini-hover":"#365d48",
  "banner-mini-back":"none",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"none",
  "banner-type":"#2a453b",
  "banner-type-back":"none",
  "banner-type-edge":"none",
  "banner-type-hover":"#365d48",
  "banner-type-back-hover":"none",
  "banner-type-edge-hover":"none",
  "banner-type-select": "#577c44",
  "banner-type-select-back": "#2a453b",
  "banner-type-select-back-edge":"none",
  "banner-color":"#2a453b",
  "banner-back":"none",
  "banner-border":"none",
  "banner-cursor":"#365d48",
  "banner-cursor-back":"none",
  "banner-room-name":"#2a453b",

  "terminal-back":"#2a453b",
  "text-primary": "#7f860f",
  "text-link": "#365d48",
  "chat-date": "#365d48",
  "chat-name": "#7f860f",
  "chat-error": "#7f860f",
  "chat-message": "#7f860f",
  "charlimit": "#365d48",
  "charlimit-over": "#365d48",
  "input-text": "#7f860f",
  "input-back": "none",
  "input-back-edge": "none", 

  "scrollbar-back": "none",
  "scrollbar-thumb": "#2a453b",
  "scrollbar-back-edge": "none",
  "scrollbar-thumb-edge": "none",

  "background-primary": "#7f860f",
  "background-code": "#346856",
  "divider": "#346856",
}
const light: ColorTheme = {
  "name": "light",
  "toolbar-back": "black",
  "toolbar-edge": "none",
  "toolbar-title": "white",
  "toolbar-button-back": "rbg(0,0,0,0)",
  "toolbar-button-logos": "white",
  "toolbar-button-back-hover": "white",
  "toolbar-button-logos-hover": "black",
  "toolbar-button-edge": "none",
  "toolbar-button-edge-hover": "none",
  "toolbar-dropdown-back": "black",
  "toolbar-dropdown-text": "white",
  "toolbar-dropdown-edge": "none",
  "toolbar-dropdown-shadow": "none",
  "toolbar-hovernames-back": "white",
  "toolbar-hovernames-text": "black",
  "toolbar-hovernames-edge": "none",
  "toolbar-slider-back": "grey",
  "toolbar-slider-back-edge": "none",
  "toolbar-slider-thumb": "white",
  "toolbar-slider-thumb-edge": "none",
  "toolbar-slider-back-hover": "white",
  "toolbar-slider-back-edge-hover": "none",
  "toolbar-slider-thumb-hover": "grey",
  "toolbar-slider-thumb-edge-hover": "none",
  "toolbar-charlimit": "white",
  "toolbar-charlimit-over": "magenta",
  "toolbar-charlimit-back": "rbg(0,0,0,0)",
  "toolbar-charlimit-over-back": "rbg(0,0,0,0)",
  "toolbar-input-text": "white",
  "toolbar-input-back": "rbg(0,0,0,0)",
  "toolbar-input-edge": "none",
  "toolbar-publish-button-text": "white",
  "toolbar-publish-button-back": "rbg(0,0,0,0)",
  "toolbar-publish-button-edge": "none",
  "toolbar-publish-button-text-hover": "black",
  "toolbar-publish-button-back-hover": "white",
  "toolbar-publish-button-edge-hover": "none",
  "toolbar-sub-button-text":"white",
  "toolbar-sub-button-back":"rbg(0,0,0,0)",
  "toolbar-sub-button-edge":"none",
  "toolbar-sub-button-text-hover":"black",
  "toolbar-sub-button-back-hover":"white",
  "toolbar-sub-button-edge-hover":"none",
  "toolbar-palette-text":"white",
  "toolbar-palette-back":"rbg(0,0,0,0)",
  "toolbar-palette-text-hover":"magenta",
  "toolbar-palette-back-hover":"rbg(0,0,0,0)",  
  "banner-line":"1px solid black",
  "banner-mini":"black",
  "banner-mini-edge":"none",
  "banner-mini-hover":"rgb(0,0,0,0.5)",
  "banner-mini-back":"rgb(0,0,0,0)",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"rgb(0,0,0,0)",
  "banner-type":"black",
  "banner-type-back":"rgb(0,0,0,0)",
  "banner-type-edge":"none",
  "banner-type-hover":"rgb(0,0,0,0.5)",
  "banner-type-back-hover":"rgb(0,0,0,0)",
  "banner-type-edge-hover":"none",
  "banner-type-select": "white",
  "banner-type-select-back": "black",
  "banner-type-select-back-edge":"none",
  "banner-color":"black",
  "banner-back":"rgb(0,0,0,0)",
  "banner-border":"none",
  "banner-cursor":"white",
  "banner-cursor-back":"rgb(0,0,0,0.5)",
  "banner-room-name":"black",
  "terminal-back":"rgb(0,0,0,0)",
  "text-primary": "black",
  "text-link": "magenta",
  "chat-date": "black",
  "chat-name": "black",
  "chat-message": "black",
  "chat-error": "red",
  "charlimit": "black",
  "charlimit-over": "magenta",
  "input-text": "black",
  "input-back": "white",
  "input-back-edge": "none", 
  "scrollbar-back": "white",
  "scrollbar-thumb": "black",
  "scrollbar-back-edge": "none",
  "scrollbar-thumb-edge": "none",
  "background-primary": "white",
  "background-code": "grey",
  "divider": "rgb(0,0,0,0.5)",
}
const pink: ColorTheme = {
  "name": "pink",
  "toolbar-back": "white",
  "toolbar-edge": "outset",
  "toolbar-title": "#E75480",
  "toolbar-button-back": "white",
  "toolbar-button-logos": "black",
  "toolbar-button-back-hover": "white",
  "toolbar-button-logos-hover": "black",
  "toolbar-button-edge": "outset",
  "toolbar-button-edge-hover": "inset",
  "toolbar-dropdown-back": "white",
  "toolbar-dropdown-text": "black",
  "toolbar-dropdown-edge": "outset",
  "toolbar-dropdown-shadow": "0px 8px 16px 0px rgba(0,0,0,1)",
  "toolbar-hovernames-back": "white",
  "toolbar-hovernames-text": "black",
  "toolbar-hovernames-edge": "outset",
  "toolbar-slider-back": "pink",
  "toolbar-slider-back-edge": "inset",
  "toolbar-slider-thumb": "white",
  "toolbar-slider-thumb-edge": "outset",
  "toolbar-slider-back-hover": "pink",
  "toolbar-slider-back-edge-hover": "inset",
  "toolbar-slider-thumb-hover": "white",
  "toolbar-slider-thumb-edge-hover": "inset",
  "toolbar-charlimit": "black",
  "toolbar-charlimit-over": "black",
  "toolbar-charlimit-back": "none",
  "toolbar-charlimit-over-back": "none",
  "toolbar-input-text": "black",
  "toolbar-input-back": "none",
  "toolbar-input-edge": "none",
  "toolbar-publish-button-text": "black",
  "toolbar-publish-button-back": "white",
  "toolbar-publish-button-edge": "outset",
  "toolbar-publish-button-text-hover": "black",
  "toolbar-publish-button-back-hover": "white",
  "toolbar-publish-button-edge-hover": "inset",
  "toolbar-sub-button-text":"black",
  "toolbar-sub-button-back":"white",
  "toolbar-sub-button-edge": "outset",
  "toolbar-sub-button-text-hover":"black",
  "toolbar-sub-button-back-hover":"white",
  "toolbar-sub-button-edge-hover":"inset",
  "toolbar-palette-text":"black",
  "toolbar-palette-back":"white",
  "toolbar-palette-text-hover":"white",
  "toolbar-palette-back-hover":"#0e0087", 
  "banner-line":"none",
  "banner-mini":"white",
  "banner-mini-edge":"none",
  "banner-mini-hover":"rgb(255,255,255,0.5)",
  "banner-mini-back":"none",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"none",
  "banner-type":"white",
  "banner-type-back":"#E75480",
  "banner-type-edge":"none",
  "banner-type-hover":"#E75480",
  "banner-type-back-hover":"rgb(255,255,255,0.5)",
  "banner-type-edge-hover":"none",
  "banner-type-select": "#E75480",
  "banner-type-select-back": "white",
  "banner-type-select-back-edge":"none",
  "banner-color":"white",
  "banner-back":"#E75480",
  "banner-border":"none",
  "banner-cursor":"#95B9C7",
  "banner-cursor-back":"rgb(255,255,255,0.5)",
  "banner-room-name":"white",
  "terminal-back":"#E75480",
  "text-primary": "white",
  "text-link": "#95B9C7",
  "chat-date": "white",
  "chat-name": "white",
  "chat-message": "white",
  "chat-error": "white",
  "charlimit": "white",
  "charlimit-over": "white",
  "input-text": "white",
  "input-back": "none",
  "input-back-edge": "none", 
  "scrollbar-back": "white",
  "scrollbar-thumb": "pink",
  "scrollbar-back-edge": "none",
  "scrollbar-thumb-edge": "none",
  "background-primary": "pink",
  "background-code": "pink",
  "divider": "white",
}
const emo: ColorTheme = {
  "name": "emo",
  "toolbar-back": "#f0007b",
  "toolbar-edge": "none",
  "toolbar-title": "black",
  "toolbar-button-back": "rbg(0,0,0,0)",
  "toolbar-button-logos": "black",
  "toolbar-button-back-hover": "black",
  "toolbar-button-logos-hover": "white",
  "toolbar-button-edge": "none",
  "toolbar-button-edge-hover": "none",
  "toolbar-dropdown-back": "purple",
  "toolbar-dropdown-text": "white",
  "toolbar-dropdown-edge": "4px solid black",
  "toolbar-dropdown-shadow": "none",
  "toolbar-hovernames-back": "black",
  "toolbar-hovernames-text": "white",
  "toolbar-hovernames-edge": "none",
  "toolbar-slider-back": "grey",
  "toolbar-slider-back-edge": "none",
  "toolbar-slider-thumb": "black",
  "toolbar-slider-thumb-edge": "none",
  "toolbar-slider-back-hover": "black",
  "toolbar-slider-back-edge-hover": "none",
  "toolbar-slider-thumb-hover": "grey",
  "toolbar-slider-thumb-edge-hover": "none",
  "toolbar-charlimit": "black",
  "toolbar-charlimit-over": "magenta",
  "toolbar-charlimit-back": "rbg(0,0,0,0)",
  "toolbar-charlimit-over-back": "rbg(0,0,0,0)",
  "toolbar-input-text": "black",
  "toolbar-input-back": "rbg(0,0,0,0)",
  "toolbar-input-edge": "none",
  "toolbar-publish-button-text": "black",
  "toolbar-publish-button-back": "rbg(0,0,0,0)",
  "toolbar-publish-button-edge": "none",
  "toolbar-publish-button-text-hover": "white",
  "toolbar-publish-button-back-hover": "black",
  "toolbar-publish-button-edge-hover": "none",
  "toolbar-sub-button-text":"black",
  "toolbar-sub-button-back":"rbg(0,0,0,0)",
  "toolbar-sub-button-edge":"none",
  "toolbar-sub-button-text-hover":"white",
  "toolbar-sub-button-back-hover":"black",
  "toolbar-sub-button-edge-hover":"none",
  "toolbar-palette-text":"black",
  "toolbar-palette-back":"rbg(0,0,0,0)",
  "toolbar-palette-text-hover":"magenta",
  "toolbar-palette-back-hover":"rbg(0,0,0,0)",  
  "banner-line":"1px solid black",
  "banner-mini":"white",
  "banner-mini-edge":"none",
  "banner-mini-hover":"rgb(255,255,255,0.5)",
  "banner-mini-back":"rgb(0,0,0,0)",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"rgb(0,0,0,0)",
  "banner-type":"white",
  "banner-type-back":"rgb(0,0,0,0)",
  "banner-type-edge":"none",
  "banner-type-hover":"rgb(255,255,255,0.5)",
  "banner-type-back-hover":"rgb(0,0,0,0)",
  "banner-type-edge-hover":"none",
  "banner-type-select": "black",
  "banner-type-select-back": "purple",
  "banner-type-select-back-edge":"none",
  "banner-color":"#ff4faa",
  "banner-back":"rgb(0,0,0,0)",
  "banner-border":"none",
  "banner-cursor":"white",
  "banner-cursor-back":"rgb(255,255,255,0.5)",
  "banner-room-name":"white",
  "terminal-back":"#f0007b",
  "text-primary": "white",
  "text-link": "purple",
  "chat-date": "white",
  "chat-name": "purple",
  "chat-message": "white",
  "chat-error": "purple",
  "charlimit": "white",
  "charlimit-over": "purple",
  "input-text": "white",
  "input-back": "black",
  "input-back-edge": "none", 
  "scrollbar-back": "black",
  "scrollbar-thumb": "white",
  "scrollbar-back-edge": "none",
  "scrollbar-thumb-edge": "none",
  "background-primary": "black",
  "background-code": "purple",
  "divider": "rgb(0,0,0,0.5)",
}
const aol: ColorTheme = {
  "name": "aol",
  "toolbar-back": "#015bee",
  "toolbar-edge": "outset #015bee",
  "toolbar-title": "white",
  "toolbar-button-back": "#015bee",
  "toolbar-button-logos": "white",
  "toolbar-button-back-hover": "#0140a8",
  "toolbar-button-logos-hover": "white",
  "toolbar-button-edge": "2px solid white",
  "toolbar-button-edge-hover": "2px solid white",
  "toolbar-dropdown-back": "white",
  "toolbar-dropdown-text": "black",
  "toolbar-dropdown-edge": "solid #015bee",
  "toolbar-dropdown-shadow": "0px 8px 16px 0px rgba(0,0,0,1)",
  "toolbar-hovernames-back": "#ece9d7",
  "toolbar-hovernames-text": "black",
  "toolbar-hovernames-edge": "outset #ece9d7",
  "toolbar-slider-back": "grey",
  "toolbar-slider-back-edge": "inset",
  "toolbar-slider-thumb": "white",
  "toolbar-slider-thumb-edge": "outset",
  "toolbar-slider-back-hover": "grey",
  "toolbar-slider-back-edge-hover": "inset",
  "toolbar-slider-thumb-hover": "white",
  "toolbar-slider-thumb-edge-hover": "inset",
  "toolbar-charlimit": "black",
  "toolbar-charlimit-over": "red",
  "toolbar-charlimit-back": "none",
  "toolbar-charlimit-over-back": "none",
  "toolbar-input-text": "black",
  "toolbar-input-back": "white",
  "toolbar-input-edge": "none",
  "toolbar-publish-button-text": "black",
  "toolbar-publish-button-back": "none",
  "toolbar-publish-button-edge": "groove",
  "toolbar-publish-button-text-hover": "grey",
  "toolbar-publish-button-back-hover": "none",
  "toolbar-publish-button-edge-hover": "groove",
  "toolbar-sub-button-text":"black",
  "toolbar-sub-button-back":"none",
  "toolbar-sub-button-edge": "groove",
  "toolbar-sub-button-text-hover":"grey",
  "toolbar-sub-button-back-hover":"none",
  "toolbar-sub-button-edge-hover":"groove",
  "toolbar-palette-text":"black",
  "toolbar-palette-back":"white",
  "toolbar-palette-text-hover":"white",
  "toolbar-palette-back-hover":"blue",
  "banner-line":"groove",
  "banner-mini":"black",
  "banner-mini-edge":"none",
  "banner-mini-hover":"grey",
  "banner-mini-back":"none",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"none",
  "banner-type":"black",
  "banner-type-back":"none",
  "banner-type-edge":"none",
  "banner-type-hover":"grey",
  "banner-type-back-hover":"none",
  "banner-type-edge-hover":"none",
  "banner-type-select": "blue",
  "banner-type-select-back": "none",
  "banner-type-select-back-edge":"none",
  "banner-color":"black",
  "banner-back":"white",
  "banner-border":"inset",
  "banner-cursor":"white",
  "banner-cursor-back":"#0e0087",
  "banner-room-name":"black",

  "terminal-back":"white",
  "text-primary": "black",
  "text-link": "blue",
  "chat-date": "blue",
  "chat-name": "red",
  "chat-error": "red",
  "chat-message": "black",
  "charlimit": "black",
  "charlimit-over": "black",
  "input-text": "black",
  "input-back": "none",
  "input-back-edge": "none", 

  "scrollbar-back": "grey",
  "scrollbar-thumb": "#ece9d7",
  "scrollbar-back-edge": "grey",
  "scrollbar-thumb-edge": "#ece9d7",

  "background-primary": "#ece9d7",
  "background-code": "white",
  "divider": "black",
}
const ds: ColorTheme = {
  "name": "ds",
  "toolbar-back": "#6b90a6",
  "toolbar-edge": "outset #6b90a6",
  "toolbar-title": "white",
  "toolbar-button-back": "#d7d7d7",
  "toolbar-button-logos": "black",
  "toolbar-button-back-hover": "grey",
  "toolbar-button-logos-hover": "black",
  "toolbar-button-edge": "2px solid black",
  "toolbar-button-edge-hover": "2px solid black",
  "toolbar-dropdown-back": "#d7d7d7",
  "toolbar-dropdown-text": "black",
  "toolbar-dropdown-edge": "outset #d7d7d7",
  "toolbar-dropdown-shadow": "0px 8px 16px 0px rgba(0,0,0,1)",
  "toolbar-hovernames-back": "#d7d7d7",
  "toolbar-hovernames-text": "black",
  "toolbar-hovernames-edge": "outset #d7d7d7",
  "toolbar-slider-back": "#f8f8f8",
  "toolbar-slider-back-edge": "none",
  "toolbar-slider-thumb": "#4d4d4d",
  "toolbar-slider-thumb-edge": "none",
  "toolbar-slider-back-hover": "#f8f8f8",
  "toolbar-slider-back-edge-hover": "none",
  "toolbar-slider-thumb-hover": "#4d4d4d",
  "toolbar-slider-thumb-edge-hover": "none",
  "toolbar-charlimit": "black",
  "toolbar-charlimit-over": "black",
  "toolbar-charlimit-back": "none",
  "toolbar-charlimit-over-back": "none",
  "toolbar-input-text": "black",
  "toolbar-input-back": "none",
  "toolbar-input-edge": "none",
  "toolbar-publish-button-text": "black",
  "toolbar-publish-button-back": "#dcdcdc",
  "toolbar-publish-button-edge": "2px solid black",
  "toolbar-publish-button-text-hover": "black",
  "toolbar-publish-button-back-hover": "#dcdcdc",
  "toolbar-publish-button-edge-hover": "2px dotted #4ea0da",
  "toolbar-sub-button-text":"#black",
  "toolbar-sub-button-back":"dcdcdc",
  "toolbar-sub-button-edge": "2px solid black",
  "toolbar-sub-button-text-hover":"black",
  "toolbar-sub-button-back-hover":"#dcdcdc",
  "toolbar-sub-button-edge-hover":"2px dotted #4ea0da",
  "toolbar-palette-text":"#575c5d",
  "toolbar-palette-back":"#d8d9d1",
  "toolbar-palette-text-hover":"#0063a4",
  "toolbar-palette-back-hover":"#4ea0da",
  "banner-line":"10px solid black",
  "banner-mini":"#575c5d",
  "banner-mini-edge":"none",
  "banner-mini-hover":"#575c5d",
  "banner-mini-back":"none",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"none",
  "banner-type":"white",
  "banner-type-back":"#6d6d6d",
  "banner-type-edge":"2px solid black",
  "banner-type-hover":"white",
  "banner-type-back-hover":"#d70000",
  "banner-type-edge-hover":"2px solid black",
  "banner-type-select": "white",
  "banner-type-select-back": "#0045c7",
  "banner-type-select-back-edge":"2px solid black",
  "banner-color":"black",
  "banner-back":"white",
  "banner-border":"2px solid #0063a4",
  "banner-cursor":"#0063a4",
  "banner-cursor-back":"#4ea0da",
  "banner-room-name":"black",

  "terminal-back":"white",
  "text-primary": "black",
  "text-link": "#4ea0da",
  "chat-date": "black",
  "chat-name": "#ef333f",
  "chat-error": "#ef333f",
  "chat-message": "black",
  "charlimit": "black",
  "charlimit-over": "black",
  "input-text": "black",
  "input-back": "none",
  "input-back-edge": "none", 

  "scrollbar-back": "none",
  "scrollbar-thumb": "grey",
  "scrollbar-back-edge": "none",
  "scrollbar-thumb-edge": "none",

  "background-primary": "#f7f7f7",
  "background-code": "white",
  "divider": "#297ef7",
}
const teletext: ColorTheme = {
  "name": "teletext",
  "toolbar-back": "blue",
  "toolbar-edge": "none",
  "toolbar-title": "yellow",
  "toolbar-button-back": "yellow",
  "toolbar-button-logos": "blue",
  "toolbar-button-back-hover": "none",
  "toolbar-button-logos-hover": "yellow",
  "toolbar-button-edge": "none",
  "toolbar-button-edge-hover": "none",
  "toolbar-dropdown-back": "black",
  "toolbar-dropdown-text": "yellow",
  "toolbar-dropdown-edge": "4px solid red",
  "toolbar-dropdown-shadow": "none",
  "toolbar-hovernames-back": "black",
  "toolbar-hovernames-text": "cyan",
  "toolbar-hovernames-edge": "4px solid red",
  "toolbar-slider-back": "cyan",
  "toolbar-slider-back-edge": "none",
  "toolbar-slider-thumb": "white",
  "toolbar-slider-thumb-edge": "none",
  "toolbar-slider-back-hover": "cyan",
  "toolbar-slider-back-edge-hover": "none",
  "toolbar-slider-thumb-hover": "white",
  "toolbar-slider-thumb-edge-hover": "none",
  "toolbar-charlimit": "cyan",
  "toolbar-charlimit-over": "yellow",
  "toolbar-charlimit-back": "rbg(0,0,0,0)",
  "toolbar-charlimit-over-back": "rbg(0,0,0,0)",
  "toolbar-input-text": "white",
  "toolbar-input-back": "rbg(0,0,0,0)",
  "toolbar-input-edge": "none",
  "toolbar-publish-button-text": "cyan",
  "toolbar-publish-button-back": "rbg(0,0,0,0)",
  "toolbar-publish-button-edge": "none",
  "toolbar-publish-button-text-hover": "yellow",
  "toolbar-publish-button-back-hover": "black",
  "toolbar-publish-button-edge-hover": "none",
  "toolbar-sub-button-text":"cyan",
  "toolbar-sub-button-back":"rbg(0,0,0,0)",
  "toolbar-sub-button-edge":"none",
  "toolbar-sub-button-text-hover":"yellow",
  "toolbar-sub-button-back-hover":"black",
  "toolbar-sub-button-edge-hover":"none",
  "toolbar-palette-text":"white",
  "toolbar-palette-back":"rbg(0,0,0,0)",
  "toolbar-palette-text-hover":"blue",
  "toolbar-palette-back-hover":"black",  
  "banner-line":"4px solid red",
  "banner-mini":"white",
  "banner-mini-edge":"none",
  "banner-mini-hover":"white",
  "banner-mini-back":"rgb(0,0,0,0)",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"rgb(0,0,0,0)",
  "banner-type":"white",
  "banner-type-back":"rgb(0,0,0,0)",
  "banner-type-edge":"none",
  "banner-type-hover":"red",
  "banner-type-back-hover":"rgb(0,0,0,0)",
  "banner-type-edge-hover":"none",
  "banner-type-select": "yellow",
  "banner-type-select-back": "blue",
  "banner-type-select-back-edge":"none",
  "banner-color":"white",
  "banner-back":"rgb(0,0,0,0)",
  "banner-border":"none",
  "banner-cursor":"blue",
  "banner-cursor-back":"black",
  "banner-room-name":"white",
  "terminal-back":"none",
  "text-primary": "white",
  "text-link": "blue",
  "chat-date": "white",
  "chat-name": "yellow",
  "chat-message": "cyan",
  "chat-error": "red",
  "charlimit": "white",
  "charlimit-over": "red",
  "input-text": "white",
  "input-back": "none",
  "input-back-edge": "none", 
  "scrollbar-back": "black",
  "scrollbar-thumb": "white",
  "scrollbar-back-edge": "none",
  "scrollbar-thumb-edge": "none",
  "background-primary": "black",
  "background-code": "blue",
  "divider": "red",
}
const myspace: ColorTheme = {
  "name": "myspace",
  "toolbar-back": "#2652d0",
  "toolbar-edge": "none",
  "toolbar-title": "white",
  "toolbar-button-back": "#6fa5f3",
  "toolbar-button-logos": "wite",
  "toolbar-button-back-hover": "#6fa5f3",
  "toolbar-button-logos-hover": "blue",
  "toolbar-button-edge": "none",
  "toolbar-button-edge-hover": "none",
  "toolbar-dropdown-back": "#deeafc",
  "toolbar-dropdown-text": "#2652d0",
  "toolbar-dropdown-edge": "2px solid #6fa5f3",
  "toolbar-dropdown-shadow": "none",
  "toolbar-hovernames-back": "#f1c67a",
  "toolbar-hovernames-text": "black",
  "toolbar-hovernames-edge": "none",
  "toolbar-slider-back": "#2652d0",
  "toolbar-slider-back-edge": "none",
  "toolbar-slider-thumb": "white",
  "toolbar-slider-thumb-edge": "none",
  "toolbar-slider-back-hover": "#2652d0",
  "toolbar-slider-back-edge-hover": "none",
  "toolbar-slider-thumb-hover": "white",
  "toolbar-slider-thumb-edge-hover": "none",
  "toolbar-charlimit": "#2652d0",
  "toolbar-charlimit-over": "#2652d0",
  "toolbar-charlimit-back": "rbg(0,0,0,0)",
  "toolbar-charlimit-over-back": "rbg(0,0,0,0)",
  "toolbar-input-text": "#2652d0",
  "toolbar-input-back": "rbg(0,0,0,0)",
  "toolbar-input-edge": "none",
  "toolbar-publish-button-text": "#2652d0",
  "toolbar-publish-button-back": "rbg(0,0,0,0)",
  "toolbar-publish-button-edge": "none",
  "toolbar-publish-button-text-hover": "#6fa5f3",
  "toolbar-publish-button-back-hover": "none",
  "toolbar-publish-button-edge-hover": "none",
  "toolbar-sub-button-text":"#2652d0",
  "toolbar-sub-button-back":"rbg(0,0,0,0)",
  "toolbar-sub-button-edge":"none",
  "toolbar-sub-button-text-hover":"#6fa5f3",
  "toolbar-sub-button-back-hover":"none",
  "toolbar-sub-button-edge-hover":"none",
  "toolbar-palette-text":"#2652d0",
  "toolbar-palette-back":"rbg(0,0,0,0)",
  "toolbar-palette-text-hover":"#6fa5f3",
  "toolbar-palette-back-hover":"white",  
  "banner-line":"20px solid #6fa5f3",
  "banner-mini":"black",
  "banner-mini-edge":"none",
  "banner-mini-hover":"black",
  "banner-mini-back":"rgb(0,0,0,0)",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"rgb(0,0,0,0)",
  "banner-type":"black",
  "banner-type-back":"rgb(0,0,0,0)",
  "banner-type-edge":"none",
  "banner-type-hover":"#6fa5f3",
  "banner-type-back-hover":"rgb(0,0,0,0)",
  "banner-type-edge-hover":"none",
  "banner-type-select": "#2652d0",
  "banner-type-select-back": "none",
  "banner-type-select-back-edge":"none",
  "banner-color":"black",
  "banner-back":"rgb(0,0,0,0)",
  "banner-border":"none",
  "banner-cursor":"#6fa5f3",
  "banner-cursor-back":"white",
  "banner-room-name":"black",
  "terminal-back":"none",
  "text-primary": "black",
  "text-link": "blue",
  "chat-date": "black",
  "chat-name": "black",
  "chat-message": "black",
  "chat-error": "#df5b50",
  "charlimit": "black",
  "charlimit-over": "black",
  "input-text": "black",
  "input-back": "none",
  "input-back-edge": "none", 
  "scrollbar-back": "#6fa5f3",
  "scrollbar-thumb": "#2652d0",
  "scrollbar-back-edge": "none",
  "scrollbar-thumb-edge": "none",
  "background-primary": "white",
  "background-code": "#2652d0",
  "divider": "#6fa5f3",
}
const runescape: ColorTheme = {
  "name": "runescape",
  "toolbar-back": "#6d604d",
  "toolbar-edge": "outset #6d604d",
  "toolbar-title": "yellow",
  "toolbar-button-back": "#554c41",
  "toolbar-button-logos": "#eb8f22",
  "toolbar-button-back-hover": "#483e33",
  "toolbar-button-logos-hover": "#eb8f22",
  "toolbar-button-edge": "2px solid #a99a85",
  "toolbar-button-edge-hover": "2px solid #a99a85",
  "toolbar-dropdown-back": "#483e33",
  "toolbar-dropdown-text": "white",
  "toolbar-dropdown-edge": "2px outset #483e33",
  "toolbar-dropdown-shadow": "0px 8px 16px 0px rgba(0,0,0,1)",
  "toolbar-hovernames-back": "#483e33",
  "toolbar-hovernames-text": "white",
  "toolbar-hovernames-edge": "outset #483e33",
  "toolbar-slider-back": "#000001",
  "toolbar-slider-back-edge": "none",
  "toolbar-slider-thumb": "#61553e",
  "toolbar-slider-thumb-edge": "none",
  "toolbar-slider-back-hover": "#000001",
  "toolbar-slider-back-edge-hover": "none",
  "toolbar-slider-thumb-hover": "#61553e",
  "toolbar-slider-thumb-edge-hover": "none",
  "toolbar-charlimit": "#eb8f22",
  "toolbar-charlimit-over": "#eb8f22",
  "toolbar-charlimit-back": "rbg(0,0,0,0)",
  "toolbar-charlimit-over-back": "rbg(0,0,0,0)",
  "toolbar-input-text": "black",
  "toolbar-input-back": "#d2c19e",
  "toolbar-input-edge": "inset #d2c19e",
  "toolbar-publish-button-text": "white",
  "toolbar-publish-button-back": "#534a3f",
  "toolbar-publish-button-edge": "outset #534a3f",
  "toolbar-publish-button-text-hover": "white",
  "toolbar-publish-button-back-hover": "#534a3f",
  "toolbar-publish-button-edge-hover": "inset #534a3f",
  "toolbar-sub-button-text":"white",
  "toolbar-sub-button-back":"#534a3f",
  "toolbar-sub-button-edge":"outset #534a3f",
  "toolbar-sub-button-text-hover":"white",
  "toolbar-sub-button-back-hover":"#534a3f",
  "toolbar-sub-button-edge-hover":"inset #534a3f",
  "toolbar-palette-text":"yellow",
  "toolbar-palette-back":"none",
  "toolbar-palette-text-hover":"#eb8f22",
  "toolbar-palette-back-hover":"black",  
  "banner-line":"20px solid #564f3f",
  "banner-mini":"#eb8f22",
  "banner-mini-edge":"none",
  "banner-mini-hover":"#eb8f22",
  "banner-mini-back":"rgb(0,0,0,0)",
  "banner-mini-edge-hover":"none",
  "banner-mini-back-hover":"rgb(0,0,0,0)",
  "banner-type":"yellow",
  "banner-type-back":"rgb(0,0,0,0)",
  "banner-type-edge":"none",
  "banner-type-hover":"#eb8f22",
  "banner-type-back-hover":"rgb(0,0,0,0)",
  "banner-type-edge-hover":"none",
  "banner-type-select": "#eb8f22",
  "banner-type-select-back": "black",
  "banner-type-select-back-edge":"none",
  "banner-color":"yellow",
  "banner-back":"#473e35",
  "banner-border":"inset",
  "banner-cursor":"#03f901",
  "banner-cursor-back":"black",
  "banner-room-name":"yellow",
  "terminal-back":"#d2c19e",
  "text-primary": "black",
  "text-link": "blue",
  "chat-date": "black",
  "chat-name": "black",
  "chat-message": "black",
  "chat-error": "#eb8f22",
  "charlimit": "black",
  "charlimit-over": "black",
  "input-text": "black",
  "input-back": "none",
  "input-back-edge": "none", 
  "scrollbar-back": "#000001",
  "scrollbar-thumb": "#61553e",
  "scrollbar-back-edge": "inset #000001",
  "scrollbar-thumb-edge": "outset #61553e",
  "background-primary": "#473e35",
  "background-code": "yellow",
  "divider": "#877c65",
}
const THEME_STORAGE_KEY = "colorTheme";

const rootElement = document.documentElement;

class ColorUtil {
  /**
   * The user's current theme
   */
  private currentTheme: ColorTheme = dark;

  /**
   * Load a saved theme, if present
   */
  constructor() {
    const themeData = localStorage.getItem(THEME_STORAGE_KEY);
    if (themeData) {
      try {
        const parsedTheme: Partial<ColorTheme> = JSON.parse(themeData);
        for (const key in parsedTheme) {
          const value = parsedTheme[key as keyof typeof parsedTheme];
          rootElement.style.setProperty(`--color-${key}`, value!);
        }
        this.currentTheme = {
          ...dark,
          ...parsedTheme,
        };
      } catch {}
    }
  }

  /**
   * Whether a color key is valid
   * @param key The color key to validate 
   */
  public isValidColorKey = (key: string) => {
    return VALID_COLOR_KEYS.includes(key);
  }

  /**
   * Whether a color value is valid
   * @param value The color to validate
   */
  public isValidColor = (value: string) => {
    return validateColor(value);
  }

  /**
   * Whether a color theme is valid
   */
  public isValidColorTheme = (theme: string) => {
    return VALID_COLOR_THEMES.includes(theme);
  }

  /**
   * Update an individual color key
   */
  public setColor = (key: string, value: string) => {
    if (!this.isValidColorKey(key)) {
      throw new Error(`Invalid color key "${key}" - use one of: ${VALID_COLOR_KEYS.join(", ")}`)
    }
    if (!this.isValidColor(value)) {
      throw new Error(`Invalid color "${value}"`);
    }
    rootElement.style.setProperty(`--color-${key}`, value);
    this.currentTheme[key as keyof typeof dark] = value;
    this.saveTheme();
  }

  /**
   * Reset all color keys to the default theme
   */
  public resetColors = () => {
    for (const key in dark) {
      const value =  dark[key as keyof typeof dark];
      rootElement.style.setProperty(`--color-${key}`, value);
    }
    this.currentTheme = dark;
    this.saveTheme();
  }
  
  /**
   * change to preset color theme
   */
   public changeTheme = (theme: string) => {   
     if(!this.isValidColorTheme(theme)) {
       throw new Error(`Invalid theme or key "${theme}" - use one of: ${VALID_COLOR_KEYS.join(", ")}`);
     }
     //optomise later by putting all themes in same array and finding by name
     const tempThemeArray = [dark,amiga,commodore,green,amber,cga,windows,dmg,light,pink,emo,aol,ds,teletext,myspace,runescape]
     const foundTheme = tempThemeArray.find(element => element.name === theme)
     if(!foundTheme){

       return
     }
     for (const key in foundTheme) {
       const value = foundTheme[key as keyof typeof foundTheme];
       rootElement.style.setProperty(`--color-${key}`, value);
     }
     this.currentTheme = foundTheme;
     this.saveTheme();
   }

  /**
   * Save the current theme changes
   */
  public saveTheme = () => {
    localStorage.setItem(THEME_STORAGE_KEY, JSON.stringify(this.currentTheme));
  }
}

export const colorUtil = new ColorUtil();
